variables:
  XDG_CACHE_HOME: pip_cache

cache:
  key: "$CI_BUILD_NAME"
  paths:
    - pip_cache

stages:
  - test
  - deploy

before_script:
  - mkdir -p pip_cache/pip
  - python --version

after_script:
  - rm -vf ~/.pypirc

python3:
  stage: test
  image: python:3.5
  script:
    - pip install -r requirements-test.txt
    - python -m unittest discover

python2:
  stage: test
  image: python:2.7
  script:
    - pip install -r requirements-test.txt
    - python -m unittest discover

deploy_pypi:
  stage: deploy
  image: python:3.5
  script:
    - pip install wheel twine
    - python setup.py check sdist bdist_wheel
    - twine upload dist/*
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/
  except:
    - branches
