cache:
  key: "$CI_JOB_NAME"
  paths:
    - vendor/ruby

variables:
  XDG_CACHE_HOME: pip_cache

cache:
  key: "$CI_BUILD_NAME"
  paths:
    - pip_cache

before_script:
  - mkdir -p pip_cache/pip
  - python --version
  - pip install -r requirements-test.txt

python3:
  image: python:3.5
  script:
    - python -m unittest discover

python2:
  image: python:2.7
  allow_failure: true
  script:
    - python -m unittest discover
